config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'welcome#index'

  devise_for :users
  resources :questions

  get 'answeres/new/:id' => "answeres#new"
  
  resources :answeres

  
  

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :student
	belongs_to :sender	  
	has_many :sender, dependent: :destroy	
	accepts_nested_attributes_for :sender 

	def check(question,sender)
	 	@question = question
	 	@sender = sender
		if @question.mail_send == false			
			@question.update(mail_send: true)		
			Questionmailer.complete_ans_email(@question,@sender).deliver		
		end
    end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	# before_action :student_signed_in?, only: [:create, :destroy]

	def index
		# @questions = Question.all
		# @students = Student.all
	end

	def new
		@students = Student.where(:role => false)  	
		@question = Question.new				
	end

	def create		
		# @ans_mail_id_temp = params[:question][:sender_attributes][:ans_mail_id]
	    @question = Question.new(:content => params[:question][:content],:student_id => params[:question][:student_id],:behaf_id => params[:question][:behaf_id],:mail_send => params[:question][:mail_send])
	    if @question.save
	    	params[:question][:sender_attributes][:ans_mail_id].split(',').each do |d|
        		@sender = Sender.new(:ans_mail_id => d, :question_id => @question.id )	    	
        		if @sender.save	    			    		
				    flash[:success] = "Question created!"	

		 			Questionmailer.welcome_email(@question,@sender).deliver
		 			# Questionmailer.complete_ans_email(@question,@sender).deliver

		 			@question.delay(run_at: 1.minutes.from_now).check(@question,@sender)
			 			# 24.hours
			 			# if @question.mail_send == false && 
			 			# 	@question.mail_send = true
			 			# 	Questionmailer.complete_ans_email(@question,@sender).deliver				 			
				 		# end
		 			# if @question.created_at > 1.day.ago && 
			 		# 	# Questionmailer.welcome_email(@question,@sender).deliver_later(wait_until: 24.hours.from_now)
			 		# 	# Questionmailer.welcome_email(@question,@sender).deliver_later(wait: 120.seconds)	
		 			# end
	    		else
	      			redirect_to 'new'
	      		end
      		end
      		redirect_to root_url
	    end
  	end


  private

    def question_params
      params.require(:question).permit(:content,:student_id,:behaf_id,:ans_mail_id,:mail_send)
    end

    def sender_params
	  params.require(:question).permit(:ans_mail_id)    
    end

   

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.erb
this is question list of Current User

app/views/questions/new.html.erb
<h1>Create a New Question</h1>

		<%= form_for (@question) do |f| %>
		    <%= f.label :Question %><br />
    		<%= f.text_area :content, autofocus: true %><br>
    		<%= f.hidden_field :student_id, value: current_student.id %>
    		<%= f.hidden_field :mail_send, value: false %>
			<%= f.label :behaf_id, "Listener" %>		
			<%= f.collection_select(:behaf_id, Student.where(:role => false), :id, :email, {:prompt => "Select One"}) %>
			<br>	

			<%= f.fields_for :sender_attributes do |c| %>
		       <%= c.label :ans_mail_id, "Reciver(Seprate by Comma(,))" %>		
				<%= c.text_field :ans_mail_id  %>
      		<% end %>  			
      		
			<%= f.submit "Send Question" %>
		<% end %>